[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Vegetation = "b8531ea1-2e78-4866-9831-a39316ef1066"

[compat]
DataFrames = "1"
Documenter = "1"
DynamicQuantities = "1"
ModelingToolkit = "10"
OrdinaryDiffEqDefault = "1"
Plots = "1"
StochasticDiffEq = "6"
Symbolics = "6"
